### ISSUE TITLE
Make `editorialgroup` optional in grammar

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iho#2]
From @andrew2net:

 there is not editorialgroup in the data. Shouldn't we change the grammar?
```
BibDataExtensionType =
    doctype?, editorialgroup+, ics*, commentperiod?
```

@opoudjis can you help here? Thanks.

_Originally posted by @andrew2net in https://github.com/relaton/relaton-iho/issues/1#issuecomment-639458101_

**Comment by opoudjis** [comment]
Making it optional, will demand editorial group within the gem
