### ISSUE TITLE
Accept references with no dash

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-iho#8]
The gem assumes that it will search for reference codes of the format "IHO S-57". But the native format of IHO references is "S57", as can be seen in mn-samples-iho, S63, section 1.3:

____
[1]	S57 edition 3.1: IHO Transfer Standard for Digital Hydrographic Data, International Hydrographic Organization (www.iho.int)
____

If the gem is given a code of the format "IHO Xnnn", it should translate the code to IHO X-nnnn.

**Comment by andrew2net** [comment]
it's done here https://github.com/relaton/relaton-iho/commit/dd83c578b89595443b4c069a1cab84da8da2788f
